export const USERS_NO_ON_RATING_PAGE = 200;
export const USERS_NO_ON_STANDINGS_PAGE = 200;
export const SUBMISSIONS_NO_ON_STATUS_PAGE = 50;

export const RECOMPUTE_RATINGS_EVERY_N_TICKS = 60;

export const PROGRESS_BAR_DEFAULT_NOISE_LEVEL = 0.28;
