export const PROBLEM_QUALITY_PRECISION_ALPHA = 10;
export const PROBLEM_QUALITY_PRECISION_BETA = 0.1;

export const PROBLEM_QUALITY_RECALL_ALPHA = 40;
export const PROBLEM_QUALITY_RECALL_BETA = 0.2;

export const PROBLEM_PRETESTS_QUALITY_ALPHA = 5;
export const PROBLEM_PRETESTS_QUALITY_BETA = 0.2;

export const PROBLEM_PEN_PAPER_DIFFICULTY_MIDPOINT = 6;
export const PROBLEM_PEN_PAPER_DIFFICULTY_MULTIPLIER = 0.3;
export const PROBLEM_PEN_PAPER_DIFFICULTY_STDEV = 0.225;

export const PROBLEM_IMPLEMENTATION_DIFFICULTY_MIDPOINT = 6;
export const PROBLEM_IMPLEMENTATION_DIFFICULTY_MULTIPLIER = 0.3;
export const PROBLEM_IMPLEMENTATION_DIFFICULTY_STDEV = 0.3;

export const PROBLEM_PEN_PAPER_DECEPTIVENESS_MIDPOINT = 5.5;
export const PROBLEM_PEN_PAPER_DECEPTIVENESS_MULTIPLIER = 0.3;
export const PROBLEM_PEN_PAPER_DECEPTIVENESS_STDEV = 0.75;

export const PROBLEM_IMPLEMENTATION_DECEPTIVENESS_MIDPOINT = 5.5;
export const PROBLEM_IMPLEMENTATION_DECEPTIVENESS_MULTIPLIER = 0.3;
export const PROBLEM_IMPLEMENTATION_DECEPTIVENESS_STDEV = 0.75;

export const PROBLEM_READING_DIFFICULTY_MIDPOINT = 5.5;
export const PROBLEM_READING_DIFFICULTY_MULTIPLIER = 0.2;
export const PROBLEM_READING_DIFFICULTY_STDEV = 0.5;

export const READING_TIME_DISTRIBUTION_PRECISION = 8;
export const READING_TIME_BASE = 200;
export const READING_TIME_SCALING_FACTOR = Math.E;

export const PEN_PAPER_SOLVING_DISTRIBUTION_PRECISION = 3;
export const PEN_PAPER_SOLVING_TIME_BASE = 1500;
export const PEN_PAPER_SOLVING_SCALING_FACTOR = 25;

export const IMPLEMENTATION_DISTRIBUTION_PRECISION = 4;
export const IMPLEMENTATION_TIME_BASE = 1200;
export const IMPLEMENTATION_SCALING_FACTOR = 16;

export const PEN_PAPER_SEARCHING_FOR_MISTAKE_DISTRIBUTION_PRECISION = 1;
export const PEN_PAPER_SEARCHING_FOR_MISTAKE_TIME_BASE = 200;
export const PEN_PAPER_SEARCHING_FOR_MISTAKE_SCALING_FACTOR = 16;

export const IMPLEMENTATION_SEARCHING_FOR_MISTAKE_DISTRIBUTION_PRECISION = 0.5;
export const IMPLEMENTATION_SEARCHING_FOR_MISTAKE_TIME_BASE = 400;
export const IMPLEMENTATION_SEARCHING_FOR_MISTAKE_SCALING_FACTOR = 16;

export const PROBABILITY_OF_PEN_PAPER_CORRECT_SCALING_FACTOR = 0.8;
export const PROBABILITY_OF_IMPLEMENTATION_CORRECT_SCALING_FACTOR = 0.8;

export const TIME_TO_SWITCH_TO_ANOTHER_PROBLEM_DISTRIBUTION_PRECISION = 14;

export const WRONG_ANSWER_PROBABILITY_IF_IMPLEMENTATION_WRONG = 0.5;
export const RUNTIME_ERROR_PROBABILITY_IF_IMPLEMENTATION_WRONG = 0.3;
export const TIME_LIMIT_EXCEEDED_PROBABILITY_IF_IMPLEMENTATION_WRONG = 0.1;
export const MEMORY_LIMIT_EXCEEDED_PROBABILITY_IF_IMPLEMENTATION_WRONG = 0.1;

export const WRONG_ANSWER_PROBABILITY_IF_PEN_PAPER_WRONG = 0.7;
export const RUNTIME_ERROR_PROBABILITY_IF_PEN_PAPER_WRONG = 0.01;
export const TIME_LIMIT_EXCEEDED_PROBABILITY_IF_PEN_PAPER_WRONG = 0.27;
export const MEMORY_LIMIT_EXCEEDED_PROBABILITY_IF_PEN_PAPER_WRONG = 0.02;
