export const PROBLEM_QUALITY_PRECISION_ALPHA = 10;
export const PROBLEM_QUALITY_PRECISION_BETA = 0.1;

export const PROBLEM_QUALITY_RECALL_ALPHA = 40;
export const PROBLEM_QUALITY_RECALL_BETA = 0.2;

export const PROBLEM_PRETESTS_QUALITY_ALPHA = 5;
export const PROBLEM_PRETESTS_QUALITY_BETA = 0.2;

export const PROBLEM_PEN_PAPER_DIFFICULTY_MIDPOINT = 6;
export const PROBLEM_PEN_PAPER_DIFFICULTY_MULTIPLIER = 0.3;
export const PROBLEM_PEN_PAPER_DIFFICULTY_STDEV = 0.225;

export const PROBLEM_IMPLEMENTATION_DIFFICULTY_MIDPOINT = 6;
export const PROBLEM_IMPLEMENTATION_DIFFICULTY_MULTIPLIER = 0.3;
export const PROBLEM_IMPLEMENTATION_DIFFICULTY_STDEV = 0.3;

export const PROBLEM_PEN_PAPER_DECEPTIVENESS_MIDPOINT = 5.5;
export const PROBLEM_PEN_PAPER_DECEPTIVENESS_MULTIPLIER = 0.15;
export const PROBLEM_PEN_PAPER_DECEPTIVENESS_STDEV = 0.75;

export const PROBLEM_IMPLEMENTATION_DECEPTIVENESS_MIDPOINT = 5.5;
export const PROBLEM_IMPLEMENTATION_DECEPTIVENESS_MULTIPLIER = 0.15;
export const PROBLEM_IMPLEMENTATION_DECEPTIVENESS_STDEV = 0.75;

export const PROBLEM_READING_DIFFICULTY_MIDPOINT = 5.5;
export const PROBLEM_READING_DIFFICULTY_MULTIPLIER = 0.2;
export const PROBLEM_READING_DIFFICULTY_STDEV = 0.5;

export const READING_TIME_DISTRIBUTION_PRECISION = 8;
export const READING_TIME_BASE = 200;
export const READING_TIME_SCALING_FACTOR = Math.E;

export const PEN_PAPER_SOLVING_DISTRIBUTION_PRECISION = 2;
export const PEN_PAPER_SOLVING_TIME_BASE = 2400;
export const PEN_PAPER_SOLVING_SCALING_FACTOR = 5;
