export const READING_BASE_XP_GAIN = 1000;
export const READING_XP_GAIN_SCALING_FACTOR = 2;

export const PEN_PAPER_SOLVING_BASE_XP_GAIN = 6000;
export const PEN_PAPER_SOLVING_XP_GAIN_SCALING_FACTOR = 3;

export const PEN_PAPER_CARE_BASE_XP_GAIN = 1000;
export const PEN_PAPER_CARE_XP_GAIN_SCALING_FACTOR = 3;

export const IMPLEMENTATION_XP_GAIN = 1000;
export const IMPLEMENTATION_XP_SCALING_FACTOR = 3;

export const IMPLEMENTATION_CARE_XP_GAIN = 1000;
export const IMPLEMENTATION_CARE_XP_SCALING_FACTOR = 3;
