name: update trimmedUsers.json

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: execute py script usersTrimmer.py
        run: |
          python ./public/scripts/usersTrimmer.py
