name: Monthly Update trimmed-users.json

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
            app-id: ${{ vars.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
            token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute py script users-trimmer.py
        run: |
          python ./public/scripts/users-trimmer.py

      - name: Set User
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
            GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
            git add -f src/app/users/trimmed-users.json
            git commit -m "Update user data" || echo "No changes to user data"
            git push
